packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@arizeai/openinference-core@2.7.1'
  - '@arizeai/openinference-instrumentation-mcp@0.2.33'
  - '@arizeai/openinference-semantic-conventions@2.12.0'
  - '@turbo/darwin-64@2.11.2'
  - '@turbo/darwin-arm64@2.11.2'
  - '@turbo/linux-64@2.11.2'
  - '@turbo/linux-arm64@2.11.2'
  - '@turbo/windows-64@2.11.2'
  - '@turbo/windows-arm64@2.11.2'
  - turbo@2.11.2
